version: "3.0"
services:
  limesurvey:
    build:
      context: 4.0/apache/
      dockerfile: Dockerfile
    volumes:
      - /tmp/upload/surveys:/var/www/html/upload/surveys
    links:
      - lime-db
    depends_on:
      - lime-db
    ports:
      - "8080:80"
    environment:
      - "DB_TYPE=pgsql"
      - "DB_PORT=5432"
      - "DB_HOST=lime-db"
      - "DB_PASSWORD=3Tjq&RYchQ8pfjS"
      - "ADMIN_PASSWORD=qJHXyCY$bLe5K86"
  lime-db:
    image: postgres:10
    volumes:
      - db-data:/var/lib/postgresql
    environment:
      - "POSTGRES_USER=limesurvey"
      - "POSTGRES_DB=limesurvey"
      - "POSTGRES_PASSWORD=G$SFN3qsLo3dQ9q"

volumes:
  db-data:/var/data/surveys
