version: "3.0"
services:
  limesurvey:
    build:
      context: 4.0/apache/
      dockerfile: Dockerfile
    volumes:
      - /tmp/upload/surveys:/var/www/html/upload/surveys
    links:
      - lime-db
    depends_on:
      - lime-db
    ports:
      - "8080:80"
    environment:
      - "DB_TYPE=pgsql"
      - "DB_PORT=5432"
      - "DB_HOST=lime-db"
      - "DB_PASSWORD=AXRBAkMxPdpSQ7B"
      - "ADMIN_PASSWORD=TRtArHa9zBKcxFb"
  lime-db:
    image: postgres:10
    volumes:
      - db-data:/var/lib/postgresql
    ports:
      - "0.0.0.0:5432:5432"
    environment:
      - "POSTGRES_USER=limesurvey"
      - "POSTGRES_DB=limesurvey"
      - "POSTGRES_PASSWORD=AXRBAkMxPdpSQ7B"

volumes:
  db-data:
    driver: local